# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'processdetails.ui'
#
# Created: Sun Aug 29 20:26:36 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 549)
        Dialog.setBaseSize(QtCore.QSize(0, 1000))
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(178, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonOK = QtGui.QPushButton(Dialog)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.horizontalLayout.addWidget(self.pushButtonOK)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 500))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 1500))
        self.tabWidget.setObjectName("tabWidget")
        self.image = QtGui.QWidget()
        self.image.setObjectName("image")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.image)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtGui.QGroupBox(self.image)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(-1)
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.groupBox_7)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setMargin(5)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.imagePathEdit = QtGui.QLineEdit(self.groupBox_7)
        self.imagePathEdit.setMaximumSize(QtCore.QSize(16777215, 20))
        self.imagePathEdit.setObjectName("imagePathEdit")
        self.horizontalLayout_8.addWidget(self.imagePathEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setMargin(5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.imageCommandLineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.imageCommandLineEdit.setObjectName("imageCommandLineEdit")
        self.horizontalLayout_9.addWidget(self.imageCommandLineEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setMargin(5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.imagePwdEdit = QtGui.QLineEdit(self.groupBox_7)
        self.imagePwdEdit.setObjectName("imagePwdEdit")
        self.horizontalLayout_10.addWidget(self.imagePwdEdit)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setMinimumSize(QtCore.QSize(90, 20))
        self.label_5.setMaximumSize(QtCore.QSize(90, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setMargin(5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.imageStartedLabel = QtGui.QLabel(self.groupBox_7)
        self.imageStartedLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.imageStartedLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.imageStartedLabel.setObjectName("imageStartedLabel")
        self.horizontalLayout_11.addWidget(self.imageStartedLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setMinimumSize(QtCore.QSize(90, 20))
        self.label_6.setMaximumSize(QtCore.QSize(90, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setMargin(5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        self.imagePidLabel = QtGui.QLabel(self.groupBox_7)
        self.imagePidLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.imagePidLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.imagePidLabel.setObjectName("imagePidLabel")
        self.horizontalLayout_12.addWidget(self.imagePidLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_7 = QtGui.QLabel(self.groupBox_7)
        self.label_7.setMinimumSize(QtCore.QSize(90, 20))
        self.label_7.setMaximumSize(QtCore.QSize(90, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setMargin(5)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_13.addWidget(self.label_7)
        self.imagePPidLabel = QtGui.QLabel(self.groupBox_7)
        self.imagePPidLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.imagePPidLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.imagePPidLabel.setObjectName("imagePPidLabel")
        self.horizontalLayout_13.addWidget(self.imagePPidLabel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.image)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.libraryTextEdit = QtGui.QTextEdit(self.groupBox_8)
        self.libraryTextEdit.setObjectName("libraryTextEdit")
        self.horizontalLayout_14.addWidget(self.libraryTextEdit)
        self.verticalLayout_7.addWidget(self.groupBox_8)
        self.tabWidget.addTab(self.image, "")
        self.performance = QtGui.QWidget()
        self.performance.setObjectName("performance")
        self.tabWidget.addTab(self.performance, "")
        self.performanceGraph = QtGui.QWidget()
        self.performanceGraph.setObjectName("performanceGraph")
        self.gridLayout_2 = QtGui.QGridLayout(self.performanceGraph)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.actualCpu = QtGui.QProgressBar(self.groupBox_3)
        self.actualCpu.setMinimumSize(QtCore.QSize(30, 0))
        self.actualCpu.setProperty("value", 24)
        self.actualCpu.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.actualCpu.setTextVisible(False)
        self.actualCpu.setOrientation(QtCore.Qt.Vertical)
        self.actualCpu.setInvertedAppearance(False)
        self.actualCpu.setTextDirection(QtGui.QProgressBar.TopToBottom)
        self.actualCpu.setObjectName("actualCpu")
        self.verticalLayout.addWidget(self.actualCpu)
        self.labelActualCpuUsage = QtGui.QLabel(self.groupBox_3)
        self.labelActualCpuUsage.setObjectName("labelActualCpuUsage")
        self.verticalLayout.addWidget(self.labelActualCpuUsage)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.qwtPlotCpuHist = Qwt5.QwtPlot(self.groupBox_2)
        self.qwtPlotCpuHist.setObjectName("qwtPlotCpuHist")
        self.horizontalLayout_5.addWidget(self.qwtPlotCpuHist)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.actualRss = QtGui.QProgressBar(self.groupBox_4)
        self.actualRss.setMinimumSize(QtCore.QSize(30, 0))
        self.actualRss.setProperty("value", 24)
        self.actualRss.setTextVisible(False)
        self.actualRss.setOrientation(QtCore.Qt.Vertical)
        self.actualRss.setObjectName("actualRss")
        self.verticalLayout_2.addWidget(self.actualRss)
        self.labelActualRss = QtGui.QLabel(self.groupBox_4)
        self.labelActualRss.setObjectName("labelActualRss")
        self.verticalLayout_2.addWidget(self.labelActualRss)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.qwtPlotRssHist = Qwt5.QwtPlot(self.groupBox)
        self.qwtPlotRssHist.setObjectName("qwtPlotRssHist")
        self.horizontalLayout_4.addWidget(self.qwtPlotRssHist)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.actualIo = QtGui.QProgressBar(self.groupBox_5)
        self.actualIo.setMinimumSize(QtCore.QSize(30, 0))
        self.actualIo.setProperty("value", 24)
        self.actualIo.setTextVisible(False)
        self.actualIo.setOrientation(QtCore.Qt.Vertical)
        self.actualIo.setObjectName("actualIo")
        self.verticalLayout_3.addWidget(self.actualIo)
        self.labelActualIo = QtGui.QLabel(self.groupBox_5)
        self.labelActualIo.setObjectName("labelActualIo")
        self.verticalLayout_3.addWidget(self.labelActualIo)
        self.gridLayout_2.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.IO = QtGui.QGroupBox(self.performanceGraph)
        self.IO.setObjectName("IO")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.IO)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.qwtPlotIoHist = Qwt5.QwtPlot(self.IO)
        self.qwtPlotIoHist.setObjectName("qwtPlotIoHist")
        self.horizontalLayout_2.addWidget(self.qwtPlotIoHist)
        self.gridLayout_2.addWidget(self.IO, 2, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.performanceGraph)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.actualTcpip = QtGui.QProgressBar(self.groupBox_6)
        self.actualTcpip.setMinimumSize(QtCore.QSize(30, 0))
        self.actualTcpip.setProperty("value", 24)
        self.actualTcpip.setTextVisible(False)
        self.actualTcpip.setOrientation(QtCore.Qt.Vertical)
        self.actualTcpip.setObjectName("actualTcpip")
        self.verticalLayout_5.addWidget(self.actualTcpip)
        self.labelActualTcpip = QtGui.QLabel(self.groupBox_6)
        self.labelActualTcpip.setObjectName("labelActualTcpip")
        self.verticalLayout_5.addWidget(self.labelActualTcpip)
        self.gridLayout_2.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.IO_2 = QtGui.QGroupBox(self.performanceGraph)
        self.IO_2.setObjectName("IO_2")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.IO_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.qwtPlotTcpipHist = Qwt5.QwtPlot(self.IO_2)
        self.qwtPlotTcpipHist.setObjectName("qwtPlotTcpipHist")
        self.horizontalLayout_7.addWidget(self.qwtPlotTcpipHist)
        self.gridLayout_2.addWidget(self.IO_2, 3, 1, 1, 1)
        self.tabWidget.addTab(self.performanceGraph, "")
        self.threads = QtGui.QWidget()
        self.threads.setObjectName("threads")
        self.tabWidget.addTab(self.threads, "")
        self.tcpip = QtGui.QWidget()
        self.tcpip.setObjectName("tcpip")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tcpip)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tcpipText = QtGui.QTextEdit(self.tcpip)
        self.tcpipText.setObjectName("tcpipText")
        self.horizontalLayout_6.addWidget(self.tcpipText)
        self.tabWidget.addTab(self.tcpip, "")
        self.security = QtGui.QWidget()
        self.security.setObjectName("security")
        self.tabWidget.addTab(self.security, "")
        self.environment = QtGui.QWidget()
        self.environment.setObjectName("environment")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.environment)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.environment)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.filterEdit = QtGui.QLineEdit(self.environment)
        self.filterEdit.setObjectName("filterEdit")
        self.horizontalLayout_3.addWidget(self.filterEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.environmentText = QtGui.QTextEdit(self.environment)
        self.environmentText.setObjectName("environmentText")
        self.verticalLayout_4.addWidget(self.environmentText)
        self.tabWidget.addTab(self.environment, "")
        self.strings = QtGui.QWidget()
        self.strings.setObjectName("strings")
        self.tabWidget.addTab(self.strings, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonOK.setText(QtGui.QApplication.translate("Dialog", "&OK", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Dialog", "Image file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Command line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Current directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Started (UTC)", None, QtGui.QApplication.UnicodeUTF8))
        self.imageStartedLabel.setText(QtGui.QApplication.translate("Dialog", "<>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Pid", None, QtGui.QApplication.UnicodeUTF8))
        self.imagePidLabel.setText(QtGui.QApplication.translate("Dialog", "<>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "PPid", None, QtGui.QApplication.UnicodeUTF8))
        self.imagePPidLabel.setText(QtGui.QApplication.translate("Dialog", "<>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Shared objects linked at startup (using ldd)", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.image), QtGui.QApplication.translate("Dialog", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.performance), QtGui.QApplication.translate("Dialog", "Performance", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "CPU usage", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActualCpuUsage.setText(QtGui.QApplication.translate("Dialog", "100%", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "CPU Usage history", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Private bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActualRss.setText(QtGui.QApplication.translate("Dialog", "1200Kb", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Private bytes history", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "IO Bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActualIo.setText(QtGui.QApplication.translate("Dialog", "1MB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.IO.setTitle(QtGui.QApplication.translate("Dialog", "IO Bytes history", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Dialog", "TCPIP Bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.labelActualTcpip.setText(QtGui.QApplication.translate("Dialog", "1MB/s", None, QtGui.QApplication.UnicodeUTF8))
        self.IO_2.setTitle(QtGui.QApplication.translate("Dialog", "TCPIP Bytes history", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.performanceGraph), QtGui.QApplication.translate("Dialog", "Performance Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.threads), QtGui.QApplication.translate("Dialog", "Threads", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tcpip), QtGui.QApplication.translate("Dialog", "TCP/IP", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.security), QtGui.QApplication.translate("Dialog", "Security", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Filter:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.environment), QtGui.QApplication.translate("Dialog", "Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.strings), QtGui.QApplication.translate("Dialog", "Strings", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

