# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systeminformation.ui'
#
# Created: Tue Apr 27 19:56:54 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 252)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.qwtPlotCpuHist_01 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_01.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_01.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_01.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_01.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_01.setObjectName("qwtPlotCpuHist_01")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_01, 0, 0, 1, 1)
        self.qwtPlotCpuHist_02 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_02.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_02.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_02.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_02.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_02.setObjectName("qwtPlotCpuHist_02")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_02, 0, 1, 1, 1)
        self.qwtPlotCpuHist_03 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_03.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_03.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_03.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_03.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_03.setObjectName("qwtPlotCpuHist_03")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_03, 0, 2, 1, 1)
        self.qwtPlotCpuHist_04 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_04.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_04.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_04.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_04.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_04.setObjectName("qwtPlotCpuHist_04")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_04, 0, 3, 1, 1)
        self.qwtPlotCpuHist_05 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_05.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_05.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_05.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_05.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_05.setObjectName("qwtPlotCpuHist_05")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_05, 0, 4, 1, 1)
        self.qwtPlotCpuHist_06 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_06.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_06.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_06.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_06.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_06.setObjectName("qwtPlotCpuHist_06")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_06, 0, 5, 1, 1)
        self.qwtPlotCpuHist_07 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_07.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_07.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_07.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_07.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_07.setObjectName("qwtPlotCpuHist_07")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_07, 0, 6, 1, 1)
        self.qwtPlotCpuHist_08 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_08.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_08.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_08.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_08.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_08.setObjectName("qwtPlotCpuHist_08")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_08, 0, 7, 1, 1)
        self.qwtPlotCpuHist_09 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_09.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_09.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_09.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_09.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_09.setObjectName("qwtPlotCpuHist_09")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_09, 1, 0, 1, 1)
        self.qwtPlotCpuHist_10 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_10.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_10.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_10.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_10.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_10.setObjectName("qwtPlotCpuHist_10")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_10, 1, 1, 1, 1)
        self.qwtPlotCpuHist_11 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_11.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_11.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_11.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_11.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_11.setObjectName("qwtPlotCpuHist_11")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_11, 1, 2, 1, 1)
        self.qwtPlotCpuHist_12 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_12.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_12.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_12.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_12.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_12.setObjectName("qwtPlotCpuHist_12")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_12, 1, 3, 1, 1)
        self.qwtPlotCpuHist_13 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_13.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_13.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_13.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_13.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_13.setObjectName("qwtPlotCpuHist_13")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_13, 1, 4, 1, 1)
        self.qwtPlotCpuHist_14 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_14.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_14.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_14.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_14.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_14.setObjectName("qwtPlotCpuHist_14")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_14, 1, 5, 1, 1)
        self.qwtPlotCpuHist_15 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_15.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_15.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_15.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_15.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_15.setObjectName("qwtPlotCpuHist_15")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_15, 1, 6, 1, 1)
        self.qwtPlotCpuHist_16 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_16.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_16.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_16.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_16.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_16.setObjectName("qwtPlotCpuHist_16")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_16, 1, 7, 1, 1)
        self.qwtPlotCpuHist_17 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_17.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_17.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_17.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_17.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_17.setObjectName("qwtPlotCpuHist_17")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_17, 2, 0, 1, 1)
        self.qwtPlotCpuHist_18 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_18.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_18.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_18.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_18.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_18.setObjectName("qwtPlotCpuHist_18")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_18, 2, 1, 1, 1)
        self.qwtPlotCpuHist_19 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_19.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_19.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_19.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_19.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_19.setObjectName("qwtPlotCpuHist_19")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_19, 2, 2, 1, 1)
        self.qwtPlotCpuHist_20 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_20.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_20.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_20.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_20.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_20.setObjectName("qwtPlotCpuHist_20")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_20, 2, 3, 1, 1)
        self.qwtPlotCpuHist_21 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_21.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_21.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_21.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_21.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_21.setObjectName("qwtPlotCpuHist_21")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_21, 2, 4, 1, 1)
        self.qwtPlotCpuHist_22 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_22.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_22.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_22.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_22.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_22.setObjectName("qwtPlotCpuHist_22")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_22, 2, 5, 1, 1)
        self.qwtPlotCpuHist_23 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_23.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_23.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_23.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_23.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_23.setObjectName("qwtPlotCpuHist_23")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_23, 2, 6, 1, 1)
        self.qwtPlotCpuHist_24 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_24.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_24.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_24.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_24.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_24.setObjectName("qwtPlotCpuHist_24")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_24, 2, 7, 1, 1)
        self.qwtPlotCpuHist_25 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_25.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_25.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_25.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_25.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_25.setObjectName("qwtPlotCpuHist_25")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_25, 3, 0, 1, 1)
        self.qwtPlotCpuHist_26 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_26.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_26.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_26.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_26.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_26.setObjectName("qwtPlotCpuHist_26")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_26, 3, 1, 1, 1)
        self.qwtPlotCpuHist_27 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_27.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_27.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_27.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_27.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_27.setObjectName("qwtPlotCpuHist_27")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_27, 3, 2, 1, 1)
        self.qwtPlotCpuHist_28 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_28.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_28.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_28.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_28.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_28.setObjectName("qwtPlotCpuHist_28")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_28, 3, 3, 1, 1)
        self.qwtPlotCpuHist_29 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_29.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_29.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_29.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_29.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_29.setObjectName("qwtPlotCpuHist_29")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_29, 3, 4, 1, 1)
        self.qwtPlotCpuHist_30 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_30.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_30.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_30.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_30.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_30.setObjectName("qwtPlotCpuHist_30")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_30, 3, 5, 1, 1)
        self.qwtPlotCpuHist_31 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_31.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_31.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_31.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_31.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_31.setObjectName("qwtPlotCpuHist_31")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_31, 3, 6, 1, 1)
        self.qwtPlotCpuHist_32 = Qwt5.QwtPlot(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_32.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_32.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_32.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_32.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_32.setObjectName("qwtPlotCpuHist_32")
        self.gridLayout.addWidget(self.qwtPlotCpuHist_32, 3, 7, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "System Information", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

