# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'systeminformation.ui'
#
# Created: Sun Apr 25 21:07:24 2010
#      by: PyQt4 UI code generator 4.6.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 354)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.qwtPlotCpuHist_01 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_01.setGeometry(QtCore.QRect(11, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_01.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_01.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_01.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_01.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_01.setObjectName("qwtPlotCpuHist_01")
        self.qwtPlotCpuHist_02 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_02.setGeometry(QtCore.QRect(57, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_02.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_02.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_02.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_02.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_02.setObjectName("qwtPlotCpuHist_02")
        self.qwtPlotCpuHist_03 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_03.setGeometry(QtCore.QRect(103, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_03.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_03.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_03.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_03.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_03.setObjectName("qwtPlotCpuHist_03")
        self.qwtPlotCpuHist_04 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_04.setGeometry(QtCore.QRect(149, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_04.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_04.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_04.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_04.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_04.setObjectName("qwtPlotCpuHist_04")
        self.qwtPlotCpuHist_05 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_05.setGeometry(QtCore.QRect(195, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_05.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_05.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_05.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_05.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_05.setObjectName("qwtPlotCpuHist_05")
        self.qwtPlotCpuHist_06 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_06.setGeometry(QtCore.QRect(241, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_06.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_06.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_06.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_06.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_06.setObjectName("qwtPlotCpuHist_06")
        self.qwtPlotCpuHist_07 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_07.setGeometry(QtCore.QRect(287, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_07.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_07.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_07.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_07.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_07.setObjectName("qwtPlotCpuHist_07")
        self.qwtPlotCpuHist_08 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_08.setGeometry(QtCore.QRect(333, 11, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_08.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_08.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_08.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_08.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_08.setObjectName("qwtPlotCpuHist_08")
        self.qwtPlotCpuHist_09 = Qwt5.QwtPlot(self.frame)
        self.qwtPlotCpuHist_09.setGeometry(QtCore.QRect(8, 60, 40, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlotCpuHist_09.sizePolicy().hasHeightForWidth())
        self.qwtPlotCpuHist_09.setSizePolicy(sizePolicy)
        self.qwtPlotCpuHist_09.setMinimumSize(QtCore.QSize(40, 40))
        self.qwtPlotCpuHist_09.setSizeIncrement(QtCore.QSize(5, 5))
        self.qwtPlotCpuHist_09.setObjectName("qwtPlotCpuHist_09")
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "System Information", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

